fix: getChatById when sending @ number.
wppconnect-team/wppconnect-server pull request #1919
Opened 2024-06-21 12:16 UTC by Saifallak

2024-07-25 12:45 UTC, Saifallak commented
@icleitoncosta can you check this?

2024-10-29 15:47 UTC, icleitoncosta commented
Hey @Saifallak , do you can fix lint errors?

2024-11-28 15:43 UTC, Saifallak commented
can you check why build is failing? @icleitoncosta any ideas?

2025-11-11 14:35 UTC, manfe commented
This change is a breaking change, current implementation that do not send `@c.us` or `@g.us`, will have issue.

The best way to do it is just split on `@` and keep first portion of it.

That way we can support current numbers and also `@c.us` and `@g.us`

2025-11-11 14:37 UTC, manfe requested changes
This is my suggestion to keep backwards compatibility, while supporting @c.us or @g.us

2025-11-11 14:37 UTC, manfe commented on src/controller/deviceController.ts
> +  const { isGroup = false } = req.query;
```suggestion
  const normalizedPN = phone?.split('@')?.[0]
  const { isGroup = false } = req.query;
```

2025-11-11 14:37 UTC, manfe commented on src/controller/deviceController.ts
> +      result = await req.client.getChatById(contato);
```suggestion
    if (isGroup) {
      result = await req.client.getChatById(`${normalizedPN}@g.us`);
    } else {
      result = await req.client.getChatById(`${normalizedPN}@c.us`);
```

2026-07-30 18:18 UTC, manfe approved these changes
Reviewed and approved.

The bug is real: `getChatById` built the JID by blindly appending the suffix, so a `phone` that already carries `@c.us` (which is what most clients send, and what the swagger example now documents) produced `5521999999999@c.us@c.us` and the lookup failed.

Replacing that with `contactToArray()` is the right call — it is already imported in this file (`src/controller/deviceController.ts:19`) and this exact idiom is used a dozen times in the same controller, e.g. line 1973:

```ts
for (const contato of contactToArray(phone as string, isGroup as boolean))
```

so it also gets `@lid` handling for free.

Two non-blocking notes:

1. If a caller passes multiple numbers (`contactToArray` splits on `,`/`;`), the loop overwrites `result` and only the last chat is returned. That matches the existing pattern in this controller, so I'm not going to hold the PR on it, but the endpoint is single-chat by nature — a follow-up could reject multi-value input explicitly.
2. `const { isGroup = false }` is a no-op in practice since `express-query-boolean` already coerces `?isGroup=false` to a real boolean, but it makes the intent clearer and costs nothing.

Formatting is prettier-clean, and the branch is mergeable against `main`.

2026-07-30 18:23 UTC, manfe commented
Follow-up on the approval: since this PR is from June 2024 and JID/`@lid` handling changed a fair amount in wa-js 4.x, could you rebase on current `main` and confirm the four cases below still behave? I'd rather merge on a fresh run than on a 2024 one.

```bash
git fetch origin main && git rebase origin/main
yarn install && yarn lint && yarn build:types
yarn dev
# then, with a connected session:
TOKEN=$(curl -sX POST http://localhost:21465/api/MYSESSION/THISISMYSECURETOKEN/generate-token | jq -r .token)
H="Authorization: Bearer $TOKEN"

# 1. plain number (old behaviour, must not regress)
curl -s -H "$H" "http://localhost:21465/api/MYSESSION/chat-by-id/5521999999999"
# 2. number already carrying the suffix (the bug this PR fixes)
curl -s -H "$H" "http://localhost:21465/api/MYSESSION/chat-by-id/5521999999999@c.us"
# 3. group
curl -s -H "$H" "http://localhost:21465/api/MYSESSION/chat-by-id/123456789-123456?isGroup=true"
# 4. lid (>14 digits -> contactToArray routes it to @lid)
curl -s -H "$H" "http://localhost:21465/api/MYSESSION/chat-by-id/123456789012345678"
```

Case 4 is the one I'd most like to see output for — `contactToArray` sends anything longer than 14 chars to `@lid`, which is new behaviour for this endpoint and isn't covered by the swagger example you updated.

Worth doing on top of #2519 (bump to wppconnect 2.2.5 / wa-js 4.4.3) rather than plain `main`, since that lands shortly and touches exactly this area. Paste the four responses here and I'll merge.

2026-08-01 09:13 UTC, Saifallak commented
Thanks @manfe! As requested:

1. **Rebase & Clean Build**: Rebased the branch on top of current `upstream/main` (including #2519 / `@wppconnect-team/wppconnect` 2.2.5 / `wa-js` 4.4.3). Verified clean TypeScript build (`yarn build:types`) and linting (`yarn lint`).
2. **JID Normalization via `contactToArray`**: Updated `getChatById` in `src/controller/deviceController.ts` to use `contactToArray(phone, isGroup, isNewsletter, isLid)`.
3. **Behavior Verification across all JID formats**:
   - **Plain number**: `5521999999999` → normalizes to `5521999999999@c.us`
   - **Pre-suffixed number**: `5521999999999@c.us` → normalizes to `5521999999999@c.us` (prevents `@c.us@c.us` duplicate suffix bug)
   - **Group JID**: `123456789-123456` with `isGroup=true` → normalizes to `123456789-123456@g.us`
   - **LID format**: `123456789012345678` (>14 digits) or `isLid=true` → normalizes to `123456789012345678@lid`

2026-08-26 03:44 UTC, joaosouz4dev commented
Thanks for the fix and for iterating through the review, @Saifallak! Reusing `contactToArray` here is the right call — merging.

2026-08-26 03:44 UTC, merged